version: "3"

tasks:
  check:
    desc: Run all checks
    deps:
      - lint
      - test
      - format

  lint:
    desc: Lint with ruff
    cmds:
      - uv run ruff check .

  format:
    desc: Format with ruff
    cmds:
      - uv run ruff format .

  test:
    desc: Run tests
    cmds:
      - uv run pytest
